// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheMovieVerse.DB;

namespace TheMovieVerse.DB.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20220530130423_DatabaseCreation")]
    partial class DatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheMovieVerse.Model.Hall", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HallName")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<long?>("TheatreId")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSeats")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TheatreId");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("TheMovieVerse.Model.Seat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("HallId")
                        .HasColumnType("bigint");

                    b.Property<string>("SeatNo")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10);

                    b.Property<long?>("TheatreId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("TheatreId");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("TheMovieVerse.Model.Theatre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TheatreName")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Theatres");
                });

            modelBuilder.Entity("TheMovieVerse.Model.Hall", b =>
                {
                    b.HasOne("TheMovieVerse.Model.Theatre", null)
                        .WithMany("Halls")
                        .HasForeignKey("TheatreId");
                });

            modelBuilder.Entity("TheMovieVerse.Model.Seat", b =>
                {
                    b.HasOne("TheMovieVerse.Model.Hall", null)
                        .WithMany("Seats")
                        .HasForeignKey("HallId");

                    b.HasOne("TheMovieVerse.Model.Theatre", null)
                        .WithMany("Seats")
                        .HasForeignKey("TheatreId");
                });
#pragma warning restore 612, 618
        }
    }
}
